version: "3.8"

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: caption_db
    restart: always
    env_file:
      - ./envs/mysql.env
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
      - caption_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: es
    environment:
      - node.name=${NODE_NAME:-es}
      - discovery.type=${DISCOVERY_TYPE:-single-node}
      - xpack.security.enabled=${XPACK_SECURITY:-false}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT:-9200}:9200"
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cat/health?h=status | grep -qE '^green|yellow'",
        ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - ${KIBANA_PORT:-5601}:5601
    networks:
      - app_network
    depends_on:
      es:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601/api/status | grep -q '200 OK'",
        ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 60s

volumes:
  caption_data:
  es_data:

networks:
  app_network:
    driver: bridge
