CREATE DATABASE IF NOT EXISTS BanditSecret;

GRANT ALL PRIVILEGES ON BanditSecret.* TO 'admin'@'%';
FLUSH PRIVILEGES;

USE BanditSecret;

CREATE TABLE IF NOT EXISTS Videos (
    Id VARCHAR(20) PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    VideoUrl VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Captions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    VideoId VARCHAR(20) NOT NULL,
    StartTime DOUBLE NOT NULL,
    EndTime DOUBLE NOT NULL,
    CaptionText Text NOT NULL,
    FOREIGN KEY (VideoId) REFERENCES Videos(Id)
);

CREATE INDEX idx_vid_start ON Captions(VideoId, StartTime);
